default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: db_development
  database: docker
  username: docker

test:
  <<: *default
  host: db_test
  database: docker
  username: docker
