version: '2'
services:
  db_test:
    build:
      context: .
      dockerfile: docker-config/postgres/Dockerfile
  db_development:
    build:
      context: .
      dockerfile: docker-config/postgres/Dockerfile

  rails:
    build:
      context: .
      dockerfile: docker-config/rails/Dockerfile

    command: >
      bash -c "bundle install & bundle exec rake db:migrate & bundle exec rake db:test:prepare & bundle exec puma -C config/puma.rb"
    environment:
      - RAILS_ENV=development
    volumes:
      - ./:/var/app/
    ports:
      - "3001:3000"
    links:
      - db_test
      - db_development

